web/router.ex
defmodule Clase2.Router do
  use Clase2.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Clase2 do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/plazas", PageController, :plazas

    get "/register", UserController, :register
    post "/register", UserController, :register

    get "/bank", BankController, :register
    post "/bank", BankController, :register

    get "/card", CardController, :register
    post "/card", CardController, :register
  end

  # Other scopes may use custom stacks.
  # scope "/api", Clase2 do
  #   pipe_through :api
  # end
end

lib/clase2/endpoint.ex
defmodule Clase2.Endpoint do
  use Phoenix.Endpoint, otp_app: :clase2

  socket "/socket", Clase2.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :clase2, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_clase2_key",
    signing_salt: "0UTfKxo8"

  plug Clase2.Router
end

lib/clase2/repo.ex
defmodule Clase2.Repo do
  use Ecto.Repo, otp_app: :clase2
end

web/models/bank.ex
defmodule Clase2.Bank do
  use Clase2.Web, :model

  schema "banks" do
    field :name, :string
    field :phone, :string
    field :has_trust, :boolean, default: false

    timestamps
  end

  @required_fields ~w(name phone has_trust)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_length(:name, min: 3, max: 20)
  end
end

web/models/card.ex
defmodule Clase2.Card do
  use Clase2.Web, :model

  schema "cards" do
    field :name, :string

    timestamps
  end

  @required_fields ~w(name)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/user.ex
defmodule Clase2.User do
  use Clase2.Web, :model

  schema "users" do
    field :age, :integer
    field :name, :string
    field :is_mexican, :boolean, default: false
    field :gender, :string

    timestamps
  end

  @required_fields ~w(age name gender)
  @optional_fields ~w(is_mexican)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_length(:name, min: 3, max: 20)
  end
end

web/controllers/bank_controller.ex
defmodule Clase2.BankController do
  use Clase2.Web, :controller

  alias Clase2.Bank
  alias Clase2.Repo
  alias Clase2.RegistrationController, as: Registration

  def register(conn, %{"bank" => bank_params}) do
  	changeset = Bank.changeset(%Bank{}, bank_params)   
    Registration.register(conn, {:bank, changeset})
  end

  
  def register(conn, _) do
  	changeset = Bank.changeset(%Bank{})
  	render(conn, "register.html", bank: changeset)
  end

end

web/controllers/card_controller.ex
defmodule Clase2.CardController do
  use Clase2.Web, :controller

  alias Clase2.Card
  alias Clase2.Repo
  alias Clase2.RegistrationController, as: Registration

  def register(conn, %{"card" => card_params}) do
  	changeset = Card.changeset(%Card{}, card_params)   
    Registration.register(conn, {:card, changeset})
  end

  
  def register(conn, _) do
  	changeset = Card.changeset(%Card{})
  	render(conn, "register.html", card: changeset)
  end

end

web/controllers/page_controller.ex
defmodule Clase2.PageController do
  use Clase2.Web, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def plazas(conn, _params) do

  	text conn, "Mis plazas son: #{Resultados.area_total_de_plazas(6, 8, 10)}"
  end
end

web/controllers/registration_controller.ex
defmodule Clase2.RegistrationController do
  use Clase2.Web, :controller

  alias Clase2.Bank
  alias Clase2.User
  alias Clase2.Repo
  alias Clase2.Card

  def register(conn, {who, changeset}) do
  	if changeset.valid? do  
	  write_registry(conn, {who, changeset})
  	else
  	  send_registry_error(conn, {who, changeset})
  	end
  end

  def send_registry_error(conn, {:bank, changeset}) do
  	conn
    |> put_flash(:error, "Please insert valid data")
  	|> render("register.html", bank: changeset)
  end

  def send_registry_error(conn, {:user, changeset}) do
  	conn
    |> put_flash(:error, "Please insert valid data")
  	|> render("register.html", user: changeset)
  end

  def write_registry(conn, {:bank, changeset}) do
  	case Repo.insert(changeset) do
  	  {:ok, bank} ->
  	    redirect conn, to: "/plazas"
  	  {:error, bank} ->
  	    send_registry_error(conn, {:bank, changeset})
  	  :else ->
  	    render(conn, "register.html", bank: changeset)
    end
  end

  def write_registry(conn, {:card, changeset}) do
  	case Repo.insert(changeset) do
  	  {:ok, card} ->
  	    redirect conn, to: "/plazas"
  	  {:error, card} ->
  	    send_registry_error(conn, {:card, changeset})
  	  :else ->
  	    render(conn, "register.html", card: changeset)
    end
  end

  def write_registry(conn, {:user, changeset}) do
  	case Repo.insert(changeset) do
  	  {:ok, user} ->
  	    redirect conn, to: "/plazas"
  	  {:error, user} ->
  	    send_registry_error(conn, {:user, changeset})
  	  :else ->
  	    render(conn, "register.html", user: changeset)
    end
  end

end

web/controllers/user_controller.ex
defmodule Clase2.UserController do
  use Clase2.Web, :controller

  alias Clase2.User
  alias Clase2.Repo
  alias Clase2.RegistrationController, as: Registration

  def register(conn, %{"user" => user_params}) do
  	changeset = User.changeset(%User{}, user_params)

  	Registration.register(conn, {:user, changeset})
  end


  def register(conn, _) do
  	changeset = User.changeset(%User{})
  	render(conn, "register.html", user: changeset)
  end

end

web/views/bank_view.ex
defmodule Clase2.BankView do
  use Clase2.Web, :view

end

web/views/card_view.ex
defmodule Clase2.CardView do
  use Clase2.Web, :view

end

web/views/error_view.ex
defmodule Clase2.ErrorView do
  use Clase2.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Clase2.LayoutView do
  use Clase2.Web, :view
end

web/views/page_view.ex
defmodule Clase2.PageView do
  use Clase2.Web, :view

  def twitter_url(username) do
  	"http://twitter.com/" <> username
  end

  def twitter_label(username) do
  	"Check " <> username <> "'s tweets!"
  end
end

web/views/user_view.ex
defmodule Clase2.UserView do
  use Clase2.Web, :view

end

web/templates/bank/register.html.eex
<head>
<body>

	<%= form_for @bank, bank_path(@conn, :register), fn f -> %>
  		First name:<br>
  		<%= text_input f, :name %><br>
	<br>
	<br>
  		number:<br>
  		<%= text_input f, :phone, type: "number" %>
	<br>
	<br>
        <%= checkbox f, :has_trust %> do you trust the bank?
	<br>
	<br>
	   
    <%= submit "Register!" %>  
	<% end %>

</body>
</head>

web/templates/card/register.html.eex
<head>
<body>

	<%= form_for @card, card_path(@conn, :register), fn f -> %>
  		
  		<br>
  		<%= text_input f, :name %><br>
	<br>
	<br>
	<br>
	   
    <%= submit "Register!" %>  
	<% end %>

</body>
</head>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Clase2!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="<%= twitter_url("grafofilia") %>"><%= twitter_label("grafofilia") %></a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/user/index.html.eex
index.html.eex

web/templates/user/register.html.eex
<head>
<body>

	<%= form_for @user, user_path(@conn, :register), fn f -> %>
  		First name:<br>
  		<%= text_input f, :name %><br>
	<br>
	<br>
  		number:<br>
  		<%= text_input f, :age, type: "number" %>
	<br>
	<br>
        <%= checkbox f, :is_mexican %> Mexican?
	<br>
	<br>
	    <label>F</label>
	    <%= radio_button f, :gender, "F" %>
	    <label>M</label>
	    <%= radio_button f, :gender, "M" %>
	    <label>NO</label>
	    <%= radio_button f, :gender, "NO" %>
  	<br>
    <%= submit "Register!" %>  
	<% end %>

</body>
</head>